### ISSUE TITLE
[390-p8] Q5 hint

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#104]
Dear @kevinamstutz , is it possible to include a hint for "two-dimensional" arrays in awk? 

I ask this because "by month, and by year" seems to require a two-dim array. However, according to the "# 2" post on [this page](https://www.unix.com/shell-programming-and-scripting/217369-how-reference-2-dimensional-array-awk.html), awk does not support two-dim arrays, and actually pastes the two columns into one. (Then I understand your code `{M[$1","$2]++}` in [the solution](https://github.com/TheDataMine/fall2020-stat39000/blob/master/project08/stat39000project08solutions.Rmd).) 

Moreover, are the students required to get the data for all the years available in `/class/datamine/data/flights/subset`? It would be helpful if we could clarify the range of years in Question 5. 

Thanks!

**Comment by kevinamstutz** [comment]
Hey @ymzhang-neo, I modified things in #108, let's see what Dr. Ward says. Thanks!

**Comment by kevinamstutz** [comment]
I think we are good here now :)
