### ISSUE TITLE
[290/390-p9] Additional suggestions

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#107]
Dear @kevinamstutz , here are some additional thoughts on the 290 and 390 Projects 9. Thank you for the consideration! (Sorry for putting everything together in the same issue post.)

##### Q1
Shall we add a hint for `.tables`? Currently the book section on SQL does not seem to include it. Or, will there be additional instructions about using SQLite3 in the terminal (so that a book section can be linked instead of directly telling the students to use `.tables`)?

##### Q2
The first hint says
> Make sure you take a look at the data dictionary for the table and column names.

Is there a separate data dictionary for the students to use? According to [the solution](https://github.com/TheDataMine/fall2020-stat29000/blob/master/project09/stat29000project09solutions.Rmd), it seems that all the students need to do is to show the data with the headers on. In that case, can we combine the two hints, maybe as follows?
> **Hint:** Make sure you take a look at the column names and get familiar with the data tables. To see the header row as a part of each query result, run the following:
```
.headers on 
``` 

##### Styles of hints for Q1-Q3 and Q4-Q7
Starting from Q4, there are no links in "Relevant topics" and there is the note referring the SQL examples. I think it better if we make the hint styles consistent. I prefer the way adopted in Q4-Q7. My reason is although different keywords all have links embedded in Q1-Q3, the links all direct to the same book section. What do you think?

##### Q9 of 390
The question says
> ... when appearing in a World Series (`WSWin`) or when league champion (`LgWin`).

[The solution](https://github.com/TheDataMine/fall2020-stat39000/blob/master/project09/stat39000project09solutions.Rmd) checks whether `WSWin` or `LgWin` is `"Y"`. What about `"N"`? I thought that `"N"` would also mean appearances, and thus checked whether the two variables equal to `""` for this question. As I am not so familiar with baseball, could you help me clarify the meanings of the values here?

**Comment by kevinamstutz** [comment]
Hey @ymzhang-neo, check out 2ab1d34. I tried to clarify things for the project and Q1. I took your suggestion for Q2 and removed the odd data dictionary hint. I changed the styles. Lastly, I'm not sure about Q9 (this project was originally written by a TA and I modified it slightly. I know nothing about baseball. To remove confusion, however, I specify putting WSwin and LgWin as Y, so hopefully that will do the trick. What do you think?

Thanks for the excellent suggestions!

**Comment by ymzhang-neo** [comment]
Dear @kevinamstutz , thank you for the updating! I like the addition of the note on the SQL code chunks! Besides, I have included two more suggestions as reviews in 2ab1d34 . Hopefully we could clarify the situation for Q9. Thanks!

**Comment by kevinamstutz** [comment]
Fixed in the newest commit
