### ISSUE TITLE
[290/390-p10] On the submission

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#111]
Dear @kevinamstutz , I like the first important note under Question 2 for Project 10 of 290 and 390 about the RMarkdown code chunk. Do you think it possible to modify the wording so that the students would realize that they do not need to run `library` or set up the database connection in each code chunk? 

I ask this because the R code chunk under Question 5 in [the project template](https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/project_template.Rmd) is
````
```{r}
library(RSQLite)

# This is where we define and initiate a connection.
con <- dbConnect(RSQLite::SQLite(), "/class/datamine/data/chinook/chinook.db")

# We can then use the connection to run queries.
dat <- dbGetQuery(con, "SELECT * FROM employees LIMIT 5;")
head(dat)
```
````
I am afraid that some students would only copy and paste things (an example on Piazza is [here](https://piazza.com/class/kdrwui8joqe1h1?cid=266)) without trimming. However, there would not be any syntax error if they repeat `library` and `dbConnect` in each code chunk. 

I am not sure how to re-phrase the note, and not sure whether this is concerning at all. So feel free to close this issue as you see fit. Thanks!

**Comment by kevinamstutz** [comment]
Thanks @ymzhang-neo, let me know what you think about eb3d486. Thanks! Going to close for now

**Comment by ymzhang-neo** [comment]
Thank you @kevinamstutz for including the note! I think it will do!
