### ISSUE TITLE
[290/390-p10] Clarifying "Batting Average"

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#112]
Dear @kevinamstutz , I would like to suggest a re-phrase of Question 4 in 290 Project 10 (and Question 3 in 390 Project 10).

Currently the question description starts with
> Calculate the Batting Average of batters between 2000 and 2010, ...

I first thought the "average" needs to be taken across players (which is a wrong understanding). Hence, I would like to suggest the following question description.
> The [Batting Average](https://en.wikipedia.org/wiki/Batting_average_(baseball)) is a metric for a batter's performance. The Batting Average in a year is calculated by H / AB (the number of hits divided by at-bats). Calculate the seasonal Batting Average for batters between 2000 and 2010 who had more than 300 at-bats in one year. List the top 5 batting averages next to `playerID`, `teamID`, and `yearID`.

What do you think?

**Comment by kevinamstutz** [comment]
I 100% agree with these modifications, thank you @ymzhang-neo!! Changes made in da08e57. Closing for now

**Comment by ymzhang-neo** [comment]
Thank you @kevinamstutz for the update!
