### ISSUE TITLE
[290/390-p10] Clarification for Purdue-IU comparison

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#115]
Dear @kevinamstutz , pardon me for raising another question on Question 7 in 290 Project 10 and Question 6 in 390 Project 10. The question is about creating a "misleading" plot that makes Purdue look better than IU. I would like to suggest that we simplify the question by saying: 
> Use the information you have in the database, and the power of R to create a ~~misleading~~ graphic that ~~makes~~ _compares_ Purdue ~~look better than~~ against IU ~~, even if just at first glance~~.

(We can even add "barplot" as a relevant topic under the question.)

I would like to explain my suggestion here. Personally, I find it a bit difficult to come up with an idea about the _misleading_ graph. I ran the code in [the solution](https://github.com/TheDataMine/fall2020-stat29000/blob/master/project10/stat29000project10solutions.Rmd), and got the following plot:
![image](https://user-images.githubusercontent.com/26282248/96822301-bb96bc80-13f7-11eb-8ded-4d2a633b8c26.png)
While the y-axis is the log-count, Purdue still has a bar shorter than than IU's. To me the plot does not seem to imply that Purdue is _better_ than IU. 

However, please let me know if there is anything that I missed. Thank you in advance for clarifying my understanding!

**Comment by kevinamstutz** [comment]
Hey @ymzhang-neo, the "misleading part" here is that people will automatically associate Gold with Purdue and Red with IU without looking at the labels. I'm not sure, I still think it would be interesting to see what students come up with?

**Comment by ymzhang-neo** [comment]
@kevinamstutz I missed replying to you again! Thanks for explaining it - I see your point given the strong impression about the colors as school identities. Let's see what the students may try :)
