### ISSUE TITLE
[290/390-p10] Require `COUNT` in 290-Q5/390-Q4?

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#116]
Dear @kevinamstutz , I have a question about the use of `COUNT(DISTINCT playerID)`. This is something required in Questions 5-7 of 290 and Questions 4-6 in 390. Those questions ask the students to get the count of unique players.

I like these questions in that they help me better understand the use of `DISTINCT`. However, shall we make it required to use `COUNT`? 

I will use 290 Question 5 as an example to explain why I ask this question. We would like to count the unique players that have more than 50 home runs (`HR`) in a season. The solution code is:
```
dbGetQuery(con, "SELECT COUNT(DISTINCT playerID) FROM batting WHERE HR>50;")
```
However, students may also manually count the players from the output of the following code:
```
dbGetQuery(con, "SELECT DISTINCT playerID FROM batting WHERE HR>50;")
```
(R even provided row index that indirectly counts the lines.)

I am guessing if we do not require `COUNT`, the students can equally get the answer. Personally, I think we do not need to impose restrictions on what code the students should use. In that case, no change of the questions is necessary. We simply need to include a note in the solution/for the grader to give full credits as long as the result is correct. What do you think?

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I completely agree. I think we will just make sure graders are fair and give credit where credit is due.

**Comment by ymzhang-neo** [comment]
Dear @kevinamstutz , thanks for the note! I think we can close this issue now.
