### ISSUE TITLE
[290/390-p11] Q1: MiB vs. MB; ls vs. du

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#119]
Dear @kevinamstutz , Question 1 asks about file sizes in MB. I am curious whether it is easy to add a brief note explaining MiB and MB. Another potential issue is the use of `ls` (listed as a relevant topic) versus `du` (not listed as a relevant topic). What do you think?

Or, we could skip adding notes, and be flexible in grading. Please read on for more details.

When attempting this question myself, I tried several different approaches: 
```
$ ls -lh /class/datamine/data/lahman/lahman.db 
-rw-rw-r-- 1 kamstut tdm-admin 63M Jun 25 11:33 /class/datamine/data/lahman/lahman.db

$ ls -l --block-size=M /class/datamine/data/lahman/lahman.db 
-rw-rw-r-- 1 kamstut tdm-admin 63M Jun 25 11:33 /class/datamine/data/lahman/lahman.db

$ ls -l --block-size=MB /class/datamine/data/lahman/lahman.db 
-rw-rw-r-- 1 kamstut tdm-admin 67MB Jun 25 11:33 /class/datamine/data/lahman/lahman.db

$ du -h /class/datamine/data/lahman/lahman.db
38M	/class/datamine/data/lahman/lahman.db

$ du -h --block-size=M /class/datamine/data/lahman/lahman.db
38M	/class/datamine/data/lahman/lahman.db

$ du -m /class/datamine/data/lahman/lahman.db
38	/class/datamine/data/lahman/lahman.db

$ du -h --block-size=MB /class/datamine/data/lahman/lahman.db
40MB	/class/datamine/data/lahman/lahman.db
```
Some students may only go so far as `ls -lh` or `du -h`, while some may use `ls -l --block-size=M` instead of `MB`. The answers from the students may not be identical. In particular, the difference between `ls` and `du` results could be large.

Another concern of mine is the distinction between MiB and MB. Personally, I have the impression that "1 MB = 1024^2 Bytes" and have not heard about MiB until recently. However, I am not sure how prevalent this impression is.

**Comment by kevinamstutz** [comment]
Great questions @ymzhang-neo!

I think it is worth it to add a quick note, I'll mention this issue when I push it. I think it is common to not know about this. I learned about this just this year. I'll make things more specific.

As far as `ls` vs `du` you can do the following to get the matching numbers:

`du -h --apparent-size`

I think we should probably accept both actual disk usage and apparent disk usage as `ls` is more common-place (I think, anyways). I'll make a note specifically saying either will be accepted.

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , thanks for adding the clarification in 1ce9c33! Looks nice! And thanks for introducing the option `--apparent-size`: I am learning something new today :)

In the UNIX chapter of the Examples Book, [the third example](https://thedatamine.github.io/the-examples-book/unix.html#why-is-the-result-of-du--b-.metadata.csv-divided-by-1024-not-the-result-of-du--k-.metadata.csv) of [`du`](https://thedatamine.github.io/the-examples-book/unix.html#du) mentioned the distinction between disk usage and actual file size. Perhaps it can be referred to in the note when the project is released?

I also get the impression that `ls` is more commonly seen than `du`. Nevertheless, shall we add `du` to the relevant topics? In [Project 3](https://thedatamine.github.io/the-examples-book/projects.html#p03-290), the use of `du -h` is listed as a hint for [Question 5](https://thedatamine.github.io/the-examples-book/projects.html#in-scholar-when-you-want-to-deal-with-really-large-amounts-of-data-you-want-to-access-scratch-you-can-read-more-here.-your-scratch-directory-on-scholar-is-located-here-scratchscholaruser.-user-is-an-environment-variable-containing-your-username.-test-it-out-echo-scratchscholaruser.-perform-the-following-actions), but `ls` was not listed. Meanwhile, the example of [`ls`](https://thedatamine.github.io/the-examples-book/unix.html#how-do-i-list-all-files-and-folders-including-hidden-files-and-folders-in-homeuserprojects-in-a-list-format-including-information-like-permissions-filesize-etc) may not seem clear enough, as the output of `ls -la` includes many additional pieces of information that may intimidate newbies. In short, adding `du` would help those students who frequently refer to examples and previous projects in the Examples Book. 

(Fairly speaking, Dr. Ward did mention the use of `ls` to check file sizes in his video for [Project 3](https://thedatamine.github.io/the-examples-book/projects.html#p03-290) (see 16'22"-18'00" of the video, where he also compared the difference between `ls` and `du`). And the students can always ask us questions.)

**Comment by kevinamstutz** [comment]
Oh great point! I forgot that was in there. I took all of your suggestions here in daa7bc8. Thanks!!
