### ISSUE TITLE
[290/390-p11] Q2: nine-digit zip codes?

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#120]
Dear @kevinamstutz , Question 2 asks the students to find zip codes that begin with "479". From [the solution](https://github.com/TheDataMine/fall2020-stat29000/blob/master/project11/stat29000project11solutions.Rmd), I notice that the condition is `WHERE zip_code LIKE "479__"`. However, this will exclude the nine-digit zip codes (found by `479%`). Using `479%` will get us many more zip codes.

May I ask which way was intended when you designed the question? I think a clarification would be helpful, especially when Question 5 also depends on Question 2. Thanks!

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I designed the question to find 5 digit zip codes. With that being said, your solution is definitely better and should be the actual solution. Updating my solution.

**Comment by kevinamstutz** [comment]
Fixed, thanks!

**Comment by ymzhang-neo** [comment]
Thanks for the clarification!
