### ISSUE TITLE
[290/390-p11] Q4 format

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#121]
Dear @kevinamstutz , Question 4 asks the students to show the query result in a particular way. However, the output may be confusing. 

I can imagine that both `+-------------+` and `|` are automatic formatting when SQL queries are submitted via terminals. However, I notice some students usually write the code directly in RMarkdown code chunks. As a result, they may not see the terminal format of the query output, and thus try to include `+-------------+`. Or, if the students use `RMariaDB::dbGetQuery`, they would not see the formatting, either.

For example, upon the first look at the question, I forgot that `+-------------+` was added automatically, and tried something like the following:
````
```{sql connection=con}
SELECT CONCAT('+-------------+\n', 
              '| Donations   |\n', 
              '+-------------+\n', 
              '| IN: ', COUNT(*), ' |\n',
              '+-------------+\n')
FROM elections WHERE state = 'IN';
```
````
Do you think there is a way of fixing this?

Also, do you think we should replace the value 1111778 in Question 4 by some fake number or a placeholder (otherwise, the students may directly use it for Question 3)?

**Comment by kevinamstutz** [comment]
I completely agree, see if the new commit is more clear? c9cc117

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , thanks for the update. It think it will do (together with bd3eee0)!

**Comment by kevinamstutz** [comment]
Thanks @ymzhang-neo!!
