### ISSUE TITLE
[290/390-p11] Q4 solution

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#122]
Dear @kevinamstutz , this is a second post on Question 4 in Project 11 for 290 and 390. I totally understand code in [the solution](https://github.com/TheDataMine/fall2020-stat29000/blob/master/project11/stat29000project11solutions.Rmd):
```
SELECT CONCAT(state, ": ", COUNT(*)) AS 'Donations' 
FROM elections WHERE state='IN';
```
It works completely fine. However, in my first attempt, I used the following code and it did not work:
```
SELECT CONCAT("IN: ", COUNT(*)) AS Donations
FROM elections WHERE state = "IN";
```
The following two screenshots show what I got when running the code in R console and in RMarkdown:
![image](https://user-images.githubusercontent.com/26282248/97071331-a06dad80-15ad-11eb-89ff-2f00a2f5f6af.png)
![image](https://user-images.githubusercontent.com/26282248/97071361-cc892e80-15ad-11eb-81b8-0ff43e2d80aa.png)

With the help from [a post online](https://stackoverflow.com/a/22112907), I managed to show the count within in CONCAT by:
```
SELECT CONCAT("IN: ", CAST(COUNT(*) AS char(7))) AS Donations
FROM elections WHERE state = "IN";
```

Do you have any clue what may lead to the different results?

I am asking this because the code in my first attempt may be some students' attempts as well. And I prefer not to suggest CAST for them so that we keep things simple. What do you think?

**Comment by kevinamstutz** [comment]
I agree completely. Does my change in bd3eee0 address this sufficiently do you think? Thanks @ymzhang-neo!!

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , it looks good! I like the requirement on the state abbreviation being dynamic instead of static. Thanks for the update!

**Comment by kevinamstutz** [comment]
Awesome! Closing. Thanks @ymzhang-neo!
