### ISSUE TITLE
[290/390-p13] Q1 on primary and secondary keys

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#131]
Dear @kevinamstutz , Question 1 in the 290 and 390 Project 13 is about the concept of primary and foreign keys. While I think the brief overview/introduction you gave in Question 1 essentially tells the entire story, will there be links for them? Seeing some examples may be helpful for the students to better understand the concepts. (Currently the two terms under "relevant topics" have no links to additional resources.)

With a quick Google search, I found the following two links: 
- https://www.tutorialspoint.com/sql/sql-primary-key.htm
- https://www.tutorialspoint.com/sql/sql-foreign-key.htm

However, I am afraid the narrative is too technical on these two pages - for example, they talk about specifying the primary key when creating a table; however, it seems that we only require the students to learn about the concept without the need to actually create a table or a database. Do you have any suggestion about other links?

**Comment by ymzhang-neo** [comment]
Also, Question 1 asks 
> Examine the `titles` table. Do you think there are any primary keys? How about foreign keys?

As foreign keys depend on primary keys in other tables, shall we include a hint asking the students to also check the columns in tables besides `titles`?

**Comment by kevinamstutz** [comment]
Maybe this link? https://www.geeksforgeeks.org/difference-between-primary-key-and-foreign-key/

As far as that hint goes, I understand what you are getting at, but I'm worried that this will just confuse students more? At the most, I would give a note that says something like:

Foreign keys always reference a primary key in another table. So if, for example, you have a table other than the `titles` table that references a column in the `titles` table, you can be sure that this column is a primary key for the `titles` table.

What do you think?

**Comment by ymzhang-neo** [comment]
Hey @kevinamstutz , good point! Asking the students to check other tables may just confuse them - I agree.

I think the link would work - thanks for suggesting it!

**Comment by kevinamstutz** [comment]
Updated, thanks!
