### ISSUE TITLE
[290-p12] Quotation marks for aliasing in SQL

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#137]
Hi @kevinamstutz , I learned some strange behavior of SQLite (or SQLite via R) when helping a student with Question 2 of 290 Project 12 yesterday. This is not an issue about project editing - I am asking it more out of curiosity. 

Question 2 requires column aliasing names that contain spaces: `Zip Code` and `Avg Temperature`. Such names require being enclosed in quotation marks. However, when used in GROUP BY and ORDER BY, the single-quotation-enclosed names seem not to work. (I will post the example code below.)

I searched online and found that some people recommend using single quotes in SQL: https://stackoverflow.com/questions/1992314/what-is-the-difference-between-single-and-double-quotes-in-sql

Do you happen to know something about the distinction between the single and double quotation marks in SQL? Thanks in advance for your sharing!

**Comment by ymzhang-neo** [comment]
```
# Connect to the database
sqlite3 /class/datamine/data/bay_area_bike_share/bay_area_bike_share.db
```
Below is the SQL code I used, with output included.
```
SELECT zip_code AS "Zip Code", 
  AVG(mean_temperature_f) AS "Avg Temparature"
FROM weather
GROUP BY "Zip Code"
ORDER BY "Avg Temparature" DESC;
/*
Zip Code|Avg Temparature
94301|62.0806010928962
95113|61.9454297407913
94041|61.3808219178082
94063|60.9113233287858
94107|60.4270122783083
*/

SELECT zip_code AS 'Zip Code', 
  AVG(mean_temperature_f) AS 'Avg Temparature'
FROM weather
GROUP BY 'Zip Code'
ORDER BY 'Avg Temparature' DESC;
/*
Zip Code|Avg Temparature
95113|61.3488118000546
*/
```

**Comment by kevinamstutz** [comment]
Great question @ymzhang-neo! I'm going to do some research and get back to you. I'm unsure myself.

**Comment by lsukova** [comment]
you didn't get back to him );
