### ISSUE TITLE
[290/390 p4] Q2 The two "states"

### ISSUE THREAD

**Issue by wang1190** [TheDataMine/the-examples-book#163]
Are the two "states" referring to the "Regular Colors" and "Wild Colors"? I'm not sure what else could be changed on the website... But it seems it will always show "Regular Colors" when refresh the page as it is listed first, so I'm not sure what I was supposed to get for this question...

**Comment by kevinamstutz** [comment]
Yep, what if I changed the wording from:

>Describe the two states (the thing that changes), and scrape the website enough to estimate x
.

To:

>Describe the two states (the thing (element or set of elements) that changes as you refresh the page), and scrape the website enough to estimate x
.

Do you think that would make it more clear?

**Comment by wang1190** [comment]
Yeah I believe that will help understanding the questions.
