### ISSUE TITLE
Folding the table of contents?

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#47]
Dear editors, 

I wonder whether the table of contents could be folded so that only the chapter titles are shown by default, and that the section titles will be shown if the reader click a particular chapter. I am referring to the behavior of [R for Data Science](https://r4ds.had.co.nz/). 

I notice this because currently there are many FAQ items shown and readers would need to scroll down to find the projects. (I know from the office hours that some students are accessing the Examples Book using the embedded browser in Brightspace, which is smaller.) 

Perhaps the folding would make the access easier? However, I am not sure whether this would require some big changes of the entire book...

Thanks!

Yumin

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I can make this change with a very very simple configuration change. I'll talk to Dr. Ward tomorrow to see if that is indeed something we should change. I think the way we currently have it set up made sense earlier on, but maybe not so much anymore. Thanks!

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo,

I spoke with Dr. Ward today and we are all on the same page. I pushed an update a98788d that should take care of this. 

Thanks!
