### ISSUE TITLE
[290-P3] Q3 ideas

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#50]
Dear @kevinamstutz , I have only suggestion for minor changes for the bullet points in Q3 (shown in _italics_). 
> * Write a command to list the files and directories within the data directory. _(You do not need to recursively list the subdirectories and files contained therein.) What are the names of the files and directors?_
> * ~~What are the names of the files?~~ Write another command to return back to your home directory. _[Yumin: I moved the first part to the previous bullet point, thinking they are more closely related]_

**Comment by kevinamstutz** [comment]
@ymzhang-neo This is much better, thanks!
