### ISSUE TITLE
[290-P3] Q4 idea

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#51]
Dear @kevinamstutz , my suggestion for Q4 is again only related to type-setting. 

### Use paragraphs
I suggest that we break the question description into paragraphs. For example, 
> ##### Let's learn about two more important concepts. `.` refers to the current working directory, or the directory displayed when you run `pwd`. Unlike `pwd` you can use this when navigating the filesystem! So, for example, if you wanted to see the contents of a file called `my_file.txt` that lives in `/home/kamstut` (so, a full path of `/home/kamstut/my_file.txt`), and you are currently in `/home/kamstut`, you could run: `cat ./my_file.txt`. 
> ##### `..` represents the parent folder or the folder in which your current folder is contained. So let's say I was in `/home/kamstut/projects/` and I wanted to get the contents of the file `/home/kamstut/my_file.txt`. You could do: `cat ../my_file.txt`. 
> ##### When you navigate a directory tree using ~~`.`,  `..`, and `~`~~ _`.` and `..`_ you create paths that are called _relative_ paths because they are _relative_ to your current directory. Alternatively, a _full_ path or (_absolute_ path) is the path starting from the root directory. So `/home/kamstut/my_file.txt` is the _absolute_ path for `my_file.txt` and `../my_file.txt` is a _relative_ path. 
> ##### Perform the following actions, in order:

### On `~`
In the third paragraph above, I also remove `~`. To my understanding (without reference to any `bash` or UNIX documentation), `~` would point to `$HOME`. I can imagine that it being used in a relative path such as `~/../../class/datamine/apps`. But I regard `~` in this example as an alias for `$HOME`. Perhaps there are other types of relative paths where `~` plays an important role?
Another reason for the removal is that in the second bullet point, the students are asked to write a relative path without using `~`.

### "Plain `cd`"
May I ask what you meant by "plain `cd`" here? Did it mean that the students should not use an absolute path?
> * Write a single command to navigate back to your home directory using a _relative_ path. Do not use `~` or plain `cd`.

Thank you for the clarification!

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I completely agree with these changes! When I put "plain `cd`" I just meant without a path argument as it goes to `~` or `$HOME` by default if no argument is provided. I clarified this in 1553124. Also, thank you for catching my use of `~`. You can absolutely have paths with `~` _without_ having those paths be relative. My mistake! Thank you!

**Comment by ymzhang-neo** [comment]
Thank you @kevinamstutz for the update and the clarification! 

I would not call my comment/question about `~` "catching a mistake", and was just not sure whether `~` is related to relative paths :) As to `cd`, I did not know that it could be used without an argument. Learning this will definitely help me save some time: Every second counts, as Dr. Ward said in (a Piazza post):
> Just remember: Every time that you take your hand off the keyboard and reach for the mouse, even if it takes just a few seconds, you actually move that much closer to your death. Sounds morbid, I know, but what I'm trying to say is that, if you can always keep your hands on the keyboard, you become that much stronger and more powerful.
