### ISSUE TITLE
[290-P3] Links in Q5 and Q6

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#52]
Hi @kevinamstutz , it seems that the links to `du` and `rmdir` in the "Relevant topics` of Q5 and Q6, respectively, do not work as intended. They currently direct the users to [the Projects section](https://thedatamine.github.io/the-examples-book/projects.html) in the Examples Book, and there seem no contents about the two commands under [the "Unix" section](https://thedatamine.github.io/the-examples-book/unix.html). Could you double check it? Thanks!

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I'm going to add `rmdir`, `mkdir`, and `du`, and fix some links in the relevant topics. Leaving this open in the meantime, great catch!

**Comment by ymzhang-neo** [comment]
Thank you @kevinamstutz for updating and fixing the links!
