### ISSUE TITLE
[1900-P3] Removing read metadata.csv from question1

### ISSUE THREAD

**Issue by IbrigaHilda** [TheDataMine/the-examples-book#54]
Dear @kevinamstutz in question 1 students are asked to read two datasets however the metadata.csv data is not used later in the project. Is the line asking to read that data a typo?

**Comment by kevinamstutz** [comment]
Dear @IbrigaHilda,

Great point. I only have them read it in to give them a little bit more practice in Question 1 with identifying the number of rows and columns, and seeing two very different files (in terms of features/observations). Given that, do you think it just causes more confusion for students? I'll just remove it if so. Thanks!
