### ISSUE TITLE
[290-p4] Overall impression

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#61]
Dear @kevinamstutz , I am not sure how well the students remember the regex grammar from last year, some of the questions could be a bit difficult. (Actually, it could also be me not having much regex experience - literally I only learned and used it in the Data Mine!) I think we may want to provide more directions or hints, or trim one or two questions and save them for a second regex project. 

Below is my impression about the questions. I will provide in separate posts more specific ideas, questions, or suggestions.  
* First of all, I think the questions are designed at a nice pace! Q1-Q3 are straight-forward given the examples in [the Unix section](https://thedatamine.github.io/the-examples-book/unix.html). Q4 extends the case in Q3 with more names of interest. Q5 is about quantifiers. Q6-Q8 demonstrate data analysis in R (including the useful `str_extract`). Important aspects of regular expression are comprehensively covered by the questions!
* However, it is a relatively long list of regex details. I think more help would be necessary (e.g., the use of parentheses).

Ah, I realize that I do not have a specific suggestion in this post after writing the paragraphs above... Please take a look at the other posts - perhaps we could use this issue for discussion in case any trimming is needed. Thanks!

**Comment by kevinamstutz** [comment]
Closing for now.
