### ISSUE TITLE
[290-p4] Additional hints

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#64]
Dear @kevinamstutz , I would suggest that we provide some additional notes and hints for the students.
* **Escape characters**. Some students may forget that they need to escape special characters. Shall we mention [this FAQ item](https://thedatamine.github.io/the-examples-book/faqs.html#faq-escape-characters) as a note for Q4? For Q6-Q8, I think a separate note on escaping characters in R is necessary. The explanation [here](https://r4ds.had.co.nz/strings.html#basic-matches) or the last paragraph under [`str_extract`](https://thedatamine.github.io/the-examples-book/r.html#r-str-extract) or  could be useful. (However, it is possible that some students may get stuck about the use of `\\` in R since they would not read about `str_extract` in Q8 until the very end.)
* I think it also helpful to include somewhere in the project [the regex cheat sheet by RStudio](https://rstudio.com/wp-content/uploads/2016/09/RegExCheatsheet.pdf). It was introduced to the students last year, and can be a supplement to the Unix `grep` examples currently in the Examples Book (e.g., the use of parentheses and the list of quantifiers).

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, quick question. What was your solution for Q4? I'm trying to figure out why we would need escape characters for that question. I agree with the rest of your comments and am making changes accordingly.

**Comment by ymzhang-neo** [comment]
Thank you @kevinamstutz ! I used the following code for Q4:
```
grep -i "\(jim\|pam\|michael\|dwight\)\!" /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l # 281
```
The following three lines illustrate how I reached my answer:
```
$ grep -i "(jim\|pam\|michael\|dwight)!" /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
bash: !": event not found
$ grep -i "(jim\|pam\|michael\|dwight)\!" /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
21649
$ grep -i "\(jim\|pam\|michael\|dwight\)\!" /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
281
```
And here is the solution:
```
$ grep -E '(Jim|Pam|Michael|Dwight)!' /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
275
```

The difference from the solution is the `grep` option `-E`. To my understanding, without `-E` I need to escape the parentheses. I added `\` to `!` because I thought that `!` would be otherwise used as a logical operator. At this moment, I am not sure why the numbers we get (281 versus 275) are different.

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, ahhh, I see. I think the best way to handle this would be to then make sure to specify that capitalization doesn't matter (and update my solution), and link the escaping characters just like you say. This makes good sense now! Thank you!

**Comment by ymzhang-neo** [comment]
@kevinamstutz Thank you for confirming it!

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , I checked the update an have another question. It is good that there are now links talking about the importance of escaping certain characters! But I am afraid that some students still do not know that it is necessary to escape the parentheses (if they did not read carefully about the option `-E` in the manual page of `grep`).

For example, I tried the following cases:
```
$ grep -i "(jim\|pam\|michael\|dwight)\!" /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
21649 # Wrong answer if not escaping parentheses
$ grep -Ei "(jim|pam|michael|dwight)!" /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
bash: !": event not found # This is related to the choice between single and double quotes
$ grep -Ei "(jim|pam|michael|dwight)\!" /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
281 # Correct answer via double quotes + escaping ! after -E
$ grep -Ei '(jim|pam|michael|dwight)!' /class/datamine/data/movies_and_tv/the_office_dialogue.csv | wc -l
281 # Correct answer via single quotes + -E
```

I will use hypothetical students as examples to illustrate what a potential mistake he could make. 
Suppose Student A did not read about `grep -E`, he would need to escape the parentheses to get the correct answer. 
* If he checks the output, he would realize that 21649 is wrong, and further debug the code.
* If, otherwise, he is happy with some output and no error, his answer (code line 1 above) would be wrong.

Meanwhile, suppose Student B reads about `grep -E`, but used double quotes, she may need to debug the second line of code above (possible by trying escaping `(`, `)`, `|`, and/or `!`, as well as reading further about extended regex). She may not be able to realize the subtle choice between single and double quotes (as [we discussed 390 Q6 solution](https://github.com/TheDataMine/fall2020-stat39000/issues/2#issuecomment-689824109)).

By the two hypothetical students, my questions are: 
* Is it possible to mention `-E` in [the FAQ on escaping characters](https://thedatamine.github.io/the-examples-book/faqs.html#faq-escape-characters)?
* If not, shall we add a link for the list of characters that need escaping in that FAQ item? (For example, [this one](https://stackoverflow.com/a/20053121).)

**Comment by ymzhang-neo** [comment]
Sorry for not asking this question earlier (I saw your commits were just two minutes ago)!

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, no problem! I completely agree. I'll update the FAQ like you mention, and also try and push students towards using single quotes so expansion doesn't take place, as well as remember to escape special characters (and I'll link to the list). I'll mention the -E in the FAQ, but push for single quotes and escaping. Does that sound good?

**Comment by ymzhang-neo** [comment]
I agree - thanks @kevinamstutz for the plan!!

By "push students towards using single quotes" I am thinking about replacing double quotes in [`grep` examples](https://thedatamine.github.io/the-examples-book/unix.html#grep) by single quotes. But please feel free to do it in a way that you think most appropriate and convenient!

**Comment by kevinamstutz** [comment]
I think 6aa5d5f should do the trick, let me know what you think!

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , thank you for the prompt updating! I only have two comments (added there). It looks really nice!

Thank you so much for your efforts (and your patience)! Nevertheless, I easily get myself into rabbit holes - so please feel free to let me know if you find I'm thinking too much!!

**Comment by kevinamstutz** [comment]
Thank YOU! I really appreciate how thorough you were (and always are)!

**Comment by kevinamstutz** [comment]
Closing this one for now.
