### ISSUE TITLE
[290-p4] Miscellaneous typesetting

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#65]
Dear @kevinamstutz , this post is about things that I notice about typesetting. I may not write everything using the most complete sentences - please let me know if anything is confusing! Thanks!

### Introduction
* Shall we remove the paragraph of "Important note" since we are requiring the students to use RStudio Server this semester?
* The link [the_office_dialogue.csv](https://www.datadepot.rcac.purdue.edu/datamine/movies-and-tv/the_office_dialogue.csv) under the section "Dataset" does not work. Could you double check it?

### Question 1
* > ~~Login to Scholar~~ Open the Terminal in RStudio ...
* > The dataset we will use is the only dataset _in the data directory (`/class/datamine/data`)_ [Yumin: This will clarify the folder to search, in case some students did not remember the directory from Project 3 or wonder whether to start.]
* In "Item(s) to submit", remove "Use `grep` and `grepl` within R to solve a data-driven problem."

### Question 2
* The main body of the question may look a bit confusing:
  > In project 3 we learned a UNIX command to quickly print the first n lines from a file. Use this command to get the headers for the dataset. ... You can count to see which column the various bits of data live in.

  It sounds like students should use `head` and explicitly report the number of columns in the dataset, which are actually not required according to "Item(s) to submit". Do you think a clarification is necessary?
* In "Item(s) to submit":
  > The line ot UNIX commands used to ~~perform the operation~~ _find the character and original dialogue line that contains "bears. beets. battlestar galactica."_ [Yumin: This is to clarify the required code, as we probably do not need the students to include also the `head` part.]

* In [the Piping & Redirection section](https://thedatamine.github.io/the-examples-book/unix.html#piping-and-redirection), is it possible to include an overview sentence for piping in the opening paragraph? Currently the opening paragraph looks like implying that the section is about redirection only.

### Question 6
I think it better if we use the link for `grep` in R (https://thedatamine.github.io/the-examples-book/r.html#r-grep) for the "Relevant topics". Currently it directs to the Unix `grep`. (The link for `grepl` is correct.)

### Question 7
I would suggest the following re-arrangement of the sentences.
> ##### 7. Modify your regular expression in (7) to find lines with 2 or more sets of direction. How many lines have more than 2 directions? Modify your code again and find how many have more than 5.
> We count the sets of direction in each line by the pairs of square brackets. 
  ```
  This is a line with [emphasize this] only 1 direction!
  This is a line with [emphasize this] 2 sets of direction, do you see the difference [shrug].
  ```
> For example, the following data line has 2 directions: `dat$text_w_direction[2789]`.

For "Item(s) to submit", shall we use `&ge;` in place of `&gt;`?

### Question 8
The "Note" looks redundant when the example is already given above. Shall we remove it?

### Solution
I notice that [the solution](https://github.com/TheDataMine/fall2020-stat29000/blob/master/project04/stat29000project04solutions.Rmd) was prepared with different numbering and some minor discrepancy compared to the questions. Could you update it accordingly?

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I think I made all of the modifications minus updating the solution, which I will do now. Thank you!

**Comment by ymzhang-neo** [comment]
Thank you @kevinamstutz for the modification!!
