### ISSUE TITLE
[290-p4] Q8 choice between `str_extract` and `str_extract_all`

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#67]
Hi @kevinamstutz , the relevant topic of Q8 is `str_extract_all` instead of `str_extract`. May I ask why one is recommended over the other? 

Basically, my question is: What would be the regex pattern that can extract each pair of `"["` and `"]"`? More details below.

I understand that the two functions differ in the following way: `str_extract` gets the first instance, while `str_extract_all` gets all the instances. Since we allow the extraction of everything between the first `"["` and the last `"]"`, the two `stringr` functions seem to do the same - at least in the following code:
```
library(stringr)

# Version 1
q8_v11 = str_extract_all(dat$text_w_direction, '\\[.*\\]')
q8_v12 = str_extract(dat$text_w_direction, '\\[.*\\]')
all.equal(unlist(q8_v11), 
          q8_v12[!is.na(q8_v12)])

# Version 2, based on solution
q8_v21 = str_extract_all(dat$text_w_direction, '(\\[.*\\])+', simplify = F)
q8_v22 = str_extract(dat$text_w_direction, '(\\[.*\\])+')
all.equal(unlist(q8_v21), 
          q8_v22[!is.na(q8_v22)])
```
(I asked about the difference of the patterns in the two versions in the previous post #66 .)

I guess the difference between `str_extract` and `str_extract_all` depends on how multiple directions in the same line are handled. I tried the four patterns: `"\\[.*\\]"`, `"(\\[.*\\])+"`, `"(\\[.*\\])"`, and `"(\\[.*\\].*)"` - `str_extract_all` using the four patterns gave the same result.
```
all.equal(
  str_extract_all(dat$text_w_direction, '\\[.*\\]'),
  str_extract_all(dat$text_w_direction, '(\\[.*\\])+', simplify = F), # the solution code
  str_extract_all(dat$text_w_direction, '(\\[.*\\])'), 
  str_extract_all(dat$text_w_direction, '(\\[.*\\].*)')
)
```
However, if we use the regex pattern that identify each pair of `"["` and `"]"`, instead of the first `"["` and the last `"]"`, I think the result of `str_extract` would differ from that of `str_extract_all`. This is why I asked the question in the second paragraph above. Could you help me clarify my understanding? 

(This is also my last post about 290 Project 4 - I should have got in my ideas earlier... Thank you so much for the consideration!!)

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I remember that I (originally) wanted the question to ask students to actually extract the text between each square bracket, using an r version of the regular expression that did something like this: `\\[[^\\]]*\\]`. If you do this, str_extract and str_extract_all are different. I think I then changed my mind and thought that it was too difficult but then didn't make the necessary changes? str_extract_all is only useful if you have multiple matches (like you said). 

What do you think we should do? I'm leaning towards removing the last question entirely as it may just be more confusing that it is useful if you do take the time to understand it. How about you?

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , when writing this post I have not compared the 390 Project 4. The question using `\\[[^\\]]*\\]` was Q10 in 390. So you already made the change for 290!

I think it a nice question for 390. The hint definitely helps me to understand the answer. The challenging parts for me are the following two: 
* I was considering negative lookahead (since we see that in Q6 of 390) and forgot `^`!
* It is my first time seeing `[^\\]]*`: It totally makes sense, but I am not sure whether I could have written it out on my own.

Or, is it okay to make it optional in 390?

**Comment by kevinamstutz** [comment]
Ha! The 390 questions help explain what the heck I was thinking a little bit better. Question 10 is definitely a more challenging question (hence the hint). It should actually be `[^\\[\\]*` which would read any number of any character but the `[` and `]` characters. I think we should make it optional as well. Going to change it.

**Comment by kevinamstutz** [comment]
How about for 29000? Do you think we should remove question 8?

**Comment by ymzhang-neo** [comment]
I think Q8 of 290 looks fine since the students already try to identify `[` and `]` in Q6 and Q7. I think Q8 is actually a nice question as it shows the task of text extraction besides all the regex detecting questions based on `grep` in Q1-Q7.

I think the workload is okay for the following reason. If a student got Q6 by this code:
```
dat$text_w_direction = grepl('\\[.*\\]', dat$text_w_direction)
```
Then he/she could use the same regex pattern in Q8, after reading the basic usage of `str_extract_all`:
```
dat$direction = str_extract_all(dat$text_w_direction, '\\[.*\\]')
```

Initially I posted this issue in order to make sure I did not mis-understand the reason for choosing `str_extract_all`. And the second half of my initial post was already addressed by Q10 of 390!

**Comment by kevinamstutz** [comment]
Okay, great! I'll just make Q10 optional for 39000. I'm sure Dr. Ward will modify things too.

**Comment by ymzhang-neo** [comment]
Sounds good - thank you Kevin!

**Comment by kevinamstutz** [comment]
Made optional in 3091276a2f123caf9164b703c30ad041c23ea3a0
