### ISSUE TITLE
Section "About" in 290 projects

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#79]
Dear @kevinamstutz , I just notice an additional section under the 290 projects: https://thedatamine.github.io/the-examples-book/projects.html#about. Is it something intended to be written there? (Not sure how to identify the commit that added those texts...) Thanks!

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, this is Dr. Wards solution to that problem (its an rmarkdown problem and hence looks a little funky there in the book). Since it doesn't show up in the table of contents, I think it'll be fine (for now), agreed?

**Comment by ymzhang-neo** [comment]
Dear @kevinamstutz , thanks for the clarification. I did not notice the word "Solution" right above it (and wondered a bit about when Dr. Ward got an appointment from Public Health)!
