### ISSUE TITLE
[290-p6] On writing bash scripts

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#81]
Dear @kevinamstutz , it seems that [the section for writing bash scripts](https://thedatamine.github.io/the-examples-book/unix.html#writing-scripts) in the Examples Book is still under preparation. Shall we utilize perhaps materials from 290 Fall 2019?
* 290 Project 7 in Fall 2019: https://datamine.purdue.edu/seminars/fall2019/stat29000project7.html

Also, how about moving Q2 to right before Q7 so that the two questions about scripts would be right next to each other?

**Comment by kevinamstutz** [comment]
Hey @ymzhang-neo, thanks! I broke this into 2 separate issues so I can keep track a little bit easier, hope that is okay!

**Comment by ymzhang-neo** [comment]
Dear @kevinamstutz no problem at all! Thank you!
