### ISSUE TITLE
[290/390-p6] Question 5 note on space

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#83]
Dear @kevinamstutz , the [Tutorials Point page on `comm`](https://www.tutorialspoint.com/unix_commands/comm.htm) gives examples that include a space ` ` between `<` and `(`. However, it would not work in the terminal. For example:
```
$ cd /class/datamine/data/flights
$ comm -23 < (cut -d, -f15 2008.csv | sort | uniq) < (cut -d, -f25 2008.csv | sort | uniq)
bash: syntax error near unexpected token `('
$ comm -23 <(cut -d, -f15 2008.csv | sort | uniq) < (cut -d, -f25 2008.csv | sort | uniq)
bash: syntax error near unexpected token `('
```
Shall we include a note saying that there should be no space between `<` and `(`?

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, yes, absolutely! Do you by any chance know why this is? I don't think I noticed this last time (at least I can't remember), and to be honest I don't understand why it makes a difference?

I'll ask Dr. Ward if you don't know either. Thanks @ymzhang-neo!

**Comment by kevinamstutz** [comment]
Apparently its this: https://superuser.com/questions/404780/what-bash-syntax-mean 

Very interesting!

**Comment by kevinamstutz** [comment]
Another link: https://tldp.org/LDP/abs/html/process-sub.html

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , thanks for searching for the explanation! I did not know the reason, and the second link seems to prescribe that no space between `<`/`>` and parentheses. 

Is it possible to include a note to the hint? For example: 
> **Hint**: https://www.tutorialspoint.com/unix_commands/comm.htm. _The examples on that page are based on [Process Substitution](https://tldp.org/LDP/abs/html/process-sub.html), which basically allows you to specify commands whose output would be used as the input of `comm`. Note that there should be_ no space _between `<` and `(`, otherwise bash would not properly recognize the code._

**Comment by kevinamstutz** [comment]
I love that hint! Adding it now, thanks @ymzhang-neo !
