### ISSUE TITLE
[P6] 29000/39000 move questions

### ISSUE THREAD

**Issue by kevinamstutz** [TheDataMine/the-examples-book#87]
Also, how about moving Q2 to right before Q7 so that the two questions about scripts would be right next to each other?

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I like the idea of the two bash script questions being back-to-back but I think question 2 is way simpler and is essentially just a #!/bin/bash line and a single line of code. What if (instead) I added a small chunk of text that shows them how they could test out their bash script if they wanted to? That way they get to sort of test out a really simple script right away at the beginning?

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , indeed Question 2 could be a bit straight-forward. Meanwhile, it could be intimidating for some students to see the new topic of writing scripts when they may still need more questions to recall awk.

It is a great idea to include some testing! It would add a bit more to the question by showing the important step of testing during programming/development lifecycles (in the broad sense).

**Comment by kevinamstutz** [comment]
Let me know what you think about 849b0b2 @ymzhang-neo. Hopefully that will make things a little bit more clear and help on Q7 as well

**Comment by ymzhang-neo** [comment]
Dear @kevinamstutz , thank you for the updating! I have just added one suggestion as a review comment there. Feel free to modify it as needed!

**Comment by kevinamstutz** [comment]
Thanks @ymzhang-neo, fixed in 0db1cc6. I'm going to close this for now :)
