### ISSUE TITLE
Typo in TA Spring 2024 Sprint 1

### ISSUE THREAD

**Issue by Lion4567714** [TheDataMine/the-examples-book#922]
Typo in [corporate-partners-appendix/modules/TAs/pages/spring2024/sprint1.adoc](../blob/main/corporate-partners-appendix/modules/TAs/pages/spring2024/sprint1.adoc?plain=1), Line 40.

> Review your team rooster via Microsoft Teams by Wednesday

should read 

>Review your team roster via Microsoft Teams by Wednesday

😃

**Comment by CaiSChen** [comment]
This has been fixed. Thank you Anders!
